version: '3'
services:
  graphql:
    build:
      context: ./graphql
    restart: always
    environment:
      PORT: 80
    ports:
      - 8080:80

  web:
    build:
      context: ./web
    links:
      - graphql:graphql
    environment:
      PORT: 80
    ports:
      - 80:80